services:
  - type: web
    name: arman-terminal
    env: rust
    buildCommand: "cargo build --release"
    startCommand: "./target/release/armanwebsite"
    envVars:
      PORT: 8080
    healthCheckPath: "/"
    plan: free
