services:
  - type: web
    name: armanwebsite
    env: rust
    plan: free
    branch: main
    region: oregon
    buildCommand: cargo build --release
    startCommand: ./target/release/armanwebsite
    autoDeploy: true
    envVars:
      - key: RUST_LOG
        value: info
