services:
  - type: web
    name: arman-terminal
    env: rust
    buildCommand: "cargo build --release"
    startCommand: "bash -lc 'cargo build --release && ./target/release/$(basename $(cargo metadata --no-deps --format-version 1 | jq -r .packages[0].name))'"
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: "/"
    plan: free
